@set allusersprofile=c:\programdata
@set appdata=c:\users\ezhax\appdata\roaming
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=desktop-k72vv4t
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=d:\programme\visualstudio\root\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=d:\programme\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set dxsdk_dir=d:\windows kits\directx\
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64\
@set frameworkdir64=c:\windows\microsoft.net\framework64\
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set fsharpinstalldir=d:\programme\visualstudio\root\common7\ide\commonextensions\microsoft\fsharp\tools
@set homedrive=c:
@set homepath=\users\ezhax
@set include=d:\programme\visualstudio\root\vc\tools\msvc\14.29.30133\atlmfc\include;d:\programme\visualstudio\root\vc\tools\msvc\14.29.30133\include;c:\program files (x86)\windows kits\netfxsdk\4.8\include\um;d:\windows kits\10\include\10.0.19041.0\ucrt;d:\windows kits\10\include\10.0.19041.0\shared;d:\windows kits\10\include\10.0.19041.0\um;d:\windows kits\10\include\10.0.19041.0\winrt;d:\windows kits\10\include\10.0.19041.0\cppwinrt
@set lib=d:\programme\visualstudio\root\vc\tools\msvc\14.29.30133\atlmfc\lib\x64;d:\programme\visualstudio\root\vc\tools\msvc\14.29.30133\lib\x64;c:\program files (x86)\windows kits\netfxsdk\4.8\lib\um\x64;d:\windows kits\10\lib\10.0.19041.0\ucrt\x64;d:\windows kits\10\lib\10.0.19041.0\um\x64
@set libpath=d:\programme\visualstudio\root\vc\tools\msvc\14.29.30133\atlmfc\lib\x64;d:\programme\visualstudio\root\vc\tools\msvc\14.29.30133\lib\x64;d:\programme\visualstudio\root\vc\tools\msvc\14.29.30133\lib\x86\store\references;d:\windows kits\10\unionmetadata\10.0.19041.0;d:\windows kits\10\references\10.0.19041.0;c:\windows\microsoft.net\framework64\v4.0.30319
@set localappdata=c:\users\ezhax\appdata\local
@set logonserver=\\desktop-k72vv4t
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=d:\programme\pvs-studio\buildtools\msbuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.8\
@set number_of_processors=12
@set onedrive=c:\users\ezhax\onedrive
@set os=windows_nt
@set path=d:\programme\visualstudio\root\common7\ide\\extensions\microsoft\intellicode\cli;d:\programme\visualstudio\root\vc\tools\msvc\14.29.30133\bin\hostx64\x64;d:\programme\visualstudio\root\common7\ide\vc\vcpackages;d:\programme\visualstudio\root\common7\ide\commonextensions\microsoft\testwindow;d:\programme\visualstudio\root\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;d:\programme\visualstudio\root\msbuild\current\bin\roslyn;d:\programme\visualstudio\root\team tools\performance tools\x64;d:\programme\visualstudio\root\team tools\performance tools;d:\programme\visualstudio\shared\common\vsperfcollectiontools\vs2019\\x64;d:\programme\visualstudio\shared\common\vsperfcollectiontools\vs2019\;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64\;d:\programme\visualstudio\root\common7\ide\commonextensions\microsoft\fsharp\tools;d:\programme\visualstudio\root\common7\tools\devinit;d:\windows kits\10\bin\10.0.19041.0\x64;d:\windows kits\10\bin\x64;d:\programme\visualstudio\root\\msbuild\current\bin;c:\windows\microsoft.net\framework64\v4.0.30319;d:\programme\visualstudio\root\common7\ide\;d:\programme\visualstudio\root\common7\tools\;d:\programme\visualstudio\root\vc\tools\msvc\14.29.30133\bin\hostx64\x64;d:\windows kits\10\bin\10.0.19041.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64;d:\windows kits\10\bin\10.0.19041.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools;d:\programme\visualstudio\root\common7\tools;d:\programme\visualstudio\root\common7\ide;c:\program files (x86)\html help workshop;d:\programme\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files\common files\oracle\java\javapath;c:\program files (x86)\common files\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files\nvidia corporation\nvidia nvdlisr;c:\program files\dotnet\;d:\programme\matlab\runtime\win64;d:\programme\matlab\bin;d:\programme\matlab\polyspace\bin;c:\users\ezhax\appdata\local\microsoft\windowsapps;c:\users\ezhax\.dotnet\tools;c:\users\ezhax\appdata\local\programs\microsoft vs code\bin;d:\programme\visualstudio\root\common7\ide\commonextensions\microsoft\cmake\cmake\bin;d:\programme\visualstudio\root\common7\ide\commonextensions\microsoft\cmake\ninja;d:\programme\visualstudio\root\common7\ide\vc\linux\bin\connectionmanagerexe
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\ezhax\appdata\local\microsoft\visualstudio\16.0_865cb8b7\devenv.exe.config
@set platform=x64
@set processor_architecture=amd64
@set processor_identifier=amd64 family 23 model 113 stepping 0, authenticamd
@set processor_level=23
@set processor_revision=7100
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtools_extensionspath_current=d:\programme\visualstudio\root\msbuild
@set pvsbuildtools_extensionspath_vs2017=c:\windows\microsoft.net\framework64\
@set pvsbuildtools_extensionspath_vs2019=d:\programme\visualstudio\root\msbuild
@set pvsbuildtools_extensionspath_vs2022=d:\programme\visualstudio\root\msbuild
@set pvsbuildtools_installdir_current=d:\programme\visualstudio\root
@set pvsbuildtools_installdir_vs2019=d:\programme\visualstudio\root
@set pvsbuildtools_netcoresdkmajorversion=5
@set pvsbuildtools_vctargetspath_current=d:\programme\visualstudio\root\msbuild\microsoft\vc\v160\
@set pvsbuildtools_visualstudioversion_current=16.0
@set pvs_netcoresdkspath=c:\program files\dotnet\sdk\5.0.401\sdks
@set servicehublogsessionkey=5526babe
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\ezhax\appdata\local\temp
@set threadedwaitdialogdpicontext=-4
@set tmp=c:\users\ezhax\appdata\local\temp
@set ucrtversion=10.0.19041.0
@set universalcrtsdkdir=d:\windows kits\10\
@set userdomain=desktop-k72vv4t
@set userdomain_roamingprofile=desktop-k72vv4t
@set username=ezhax
@set userprofile=c:\users\ezhax
@set vcideinstalldir=d:\programme\visualstudio\root\common7\ide\vc\
@set vcinstalldir=d:\programme\visualstudio\root\vc\
@set vctoolsinstalldir=d:\programme\visualstudio\root\vc\tools\msvc\14.29.30133\
@set vctoolsredistdir=d:\programme\visualstudio\root\vc\redist\msvc\14.29.30133\
@set vctoolsversion=14.29.30133
@set visualstudiodir=c:\users\ezhax\documents\visual studio 2019
@set visualstudioedition=microsoft visual studio community 2019
@set visualstudioversion=16.0
@set vs160comntools=d:\programme\visualstudio\root\common7\tools\
@set vsappiddir=d:\programme\visualstudio\root\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x64
@set vscmd_arg_tgt_arch=x64
@set vscmd_ver=16.11.4
@set vsinstalldir=d:\programme\visualstudio\root\
@set vslang=1033
@set vsskuedition=community
@set windir=c:\windows
@set windowslibpath=d:\windows kits\10\unionmetadata\10.0.19041.0;d:\windows kits\10\references\10.0.19041.0
@set windowssdkbinpath=d:\windows kits\10\bin\
@set windowssdkdir=d:\windows kits\10\
@set windowssdklibversion=10.0.19041.0\
@set windowssdkverbinpath=d:\windows kits\10\bin\10.0.19041.0\
@set windowssdkversion=10.0.19041.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\
@set __devinit_path=d:\programme\visualstudio\root\common7\tools\devinit\devinit.exe
@set __dotnet_add_64bit=1
@set __dotnet_preferred_bitness=64
@set __vscmd_preinit_path=d:\programme\visualstudio\root\vc\tools\msvc\14.29.30133\bin\hostx64\x64;d:\windows kits\10\bin\10.0.19041.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64;d:\windows kits\10\bin\10.0.19041.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools;d:\programme\visualstudio\root\common7\tools;d:\programme\visualstudio\root\common7\ide;c:\program files (x86)\html help workshop;d:\programme\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files\common files\oracle\java\javapath;c:\program files (x86)\common files\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files\nvidia corporation\nvidia nvdlisr;c:\program files\dotnet\;d:\programme\matlab\runtime\win64;d:\programme\matlab\bin;d:\programme\matlab\polyspace\bin;c:\users\ezhax\appdata\local\microsoft\windowsapps;c:\users\ezhax\.dotnet\tools;c:\users\ezhax\appdata\local\programs\microsoft vs code\bin
@set __vscmd_script_err_count=0

@call "cl.exe" @"C:\Users\ezhax\Desktop\ezrl\injector\main.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1